# Site
repository: sproogen/luisgomes24.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luís Gomes
title: Software Engineer - Data Science and AI
email: luisgomes24.97@gmail.com 
#website: luisgomes24.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: luisgomes_24
github_username:  luisgomes24

# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: luisgomes24
linkedin_username: luisgomes24
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

#Additional icon links
# additional_links:
# - title: ResearcherGate
#   icon: fab fa-researchgate
#   url: https://www.researchgate.net/profile/Luis_Gomes45
    # - title: another link
    #     icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
    #     url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/luis-gomes.png
about_content: | # this will include new lines to allow paragraphs
  Technological advances have always attracted my interest due to all the possibilities given to the general population. This liking has evolved over the years, especially in the Computer Science field.

  As a researcher at IST and last year student at University of Minho, my formation was marked by fields with a strong presence at the present time, such as Artificial Intelligence and Data Science.

  Allied to the studies, I always involved myself in extra-curricular activities, particularly in sports, with the practice of football and kickboxing. Also in music, playing as a percussionist at Banda Filarmónica de Revelhe (philarmonic band). 


content:
#   - title: Projects # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Instituto Superior Técnico - MARÉ Project
        link: https://www.mare-project.org/
        # link_text: boringcompany.com
        sub_title: Junior Software Engineer (Backend and ML)
        caption: August 2020 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Back-end development for "IST Go!", a mobile app to help students to avoid crowded places in university campi during COVID-19 pandemic
            - Creation of ML models

                - Anomaly Detection - Detection of anomalous events based on the number of devices connected to Wi-fi APs in different buildings and zones
                - Approximation - Estimation of the approximate number of people in each zone
                - Forecasting - Prediction of the expected number of people for each zone based on previous events
      - layout: left
        title: ISLab - Algoritmi Centre
        link: http://algoritmi.uminho.pt/
        # link_text: boringcompany.com
        sub_title: Researcher
        caption: October 2018 - December 2019
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Development of a software to collect pavement images and degradations information
            - Development of a prototype to visualise pavement data
            - Study of Computer Vision techniques and Deep Learning models to classify the pavement   

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Minho
        caption: 2015 - Present
        sub_title: MSc Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
            Specializations: **Intelligent Systems** and **Data Science**
            - Machine Learning and Knowledge Extraction
            - Neural Networks and Deep Learning 
            - Large Data Set Management
            - Statistical Learning
            - Intelligent Agents and Autonomous Systems
    
            - Software Systems Development
            - Operating Systems
            - Computer Networks
            - Databases
            - Algorithms and Complexity

#   - title: Publications
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Coming Soon ... 
            
            
#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#       - Rock climbing
#       - Gaming
#       - Knitting
#       - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#       Look at this cool image  
#       ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag